@startuml UseCase5
title Diagramme de cas d'utilisation des labels

left to right direction
skinparam style strictuml
skinparam backgroundColor #EEEBDC

actor Utilisateur #Orange;line:Orange;line.bold

package "Gestion des labels" {
    usecase "== Créer un label" as UC18 #PaleGreen;line:Green;line.bold
    usecase "== Ajouter un label à une activité" as UC19 #PaleGreen;line:Green;line.bold
    usecase "== Ajouter un label à une tâche" as UC20 #PaleGreen;line:Green;line.bold
}

Utilisateur -- UC18
Utilisateur -- UC19
Utilisateur -- UC20

@enduml