@startuml UseCase4
title Diagramme de cas d'utilisation des périodes de travail

left to right direction
skinparam style strictuml
skinparam backgroundColor #EEEBDC

actor Utilisateur #Orange;line:Orange;line.bold

package "Gestion des périodes de travail" {
    usecase "== Créer une période de travail" as UC4 #PaleGreen;line:Green;line.bold
    usecase "== Afficher les périodes de travail" as UC11 #PaleGreen;line:Green;line.bold
    usecase "== Afficher les périodes de travail d'une tâche" as UC12 #PaleGreen;line:Green;line.bold
    usecase "== Afficher les périodes de travail d'un développeur" as UC13 #PaleGreen;line:Green;line.bold
}



Utilisateur -- UC4
Utilisateur -- UC11
Utilisateur -- UC12
Utilisateur -- UC13

@enduml