' ------------------------------------------------------------------------------------------------------------ '
' -------------------------------------------------- DATA ---------------------------------------------------- '
' ------------------------------------------------------------------------------------------------------------ '

!$dataFormat = {
    "entity": "Développeur", 
    "name": "Création d'un développeur",
    "demande": "Demande la création d'un développeur", 
    "create": "CreeDeveloppeur(nom, prenom, alias)", 
    "requirements": [
        "nom",
        "prénom",
        "alias"
    ],
    "preconditions": [
        "Vérifie l'unicité de l'alias"
    ],
    "postconditions": [
        {
            "entity": "Développeur",
            "name": "Le développeur est créé" 
        }
    ]
}



' ------------------------------------------------------------------------------------------------------------ '
' -------------------------------------------------- CODE ---------------------------------------------------- '
' ------------------------------------------------------------------------------------------------------------ '
skinparam style strictuml
skinparam sequenceArrowThickness 2
skinparam backgroundColor #EEEBDC
skinparam classFontName Aapex

!procedure $requirement($nameTemp) 
    ' CLI --> Utilisateur ++ : Demande $nameTemp
    ' Utilisateur -> CLI -- : Saisit $nameTemp
    $nameTemp
!endprocedure

!procedure $precondition($nameTemp) 
    SuiPro -> SuiPro : $nameTemp
!endprocedure

!procedure $postcondition($postconditionTemp) 
    Entity -> $postconditionTemp.entity ** : $postconditionTemp.name
!endprocedure

!procedure $generatePostcondition($dataTemp)
    !if $dataTemp.postconditions
            !foreach $postcondition in $dataTemp.postconditions
                $postcondition($postcondition)
            !endfor
    !endif
!endprocedure

!procedure $generateRequirement($dataTemp)
    !foreach $requirement in $dataTemp.requirements
        $requirement($requirement)
    !endfor
!endprocedure

!procedure $generatePrecondition($dataTemp)
    !if $dataTemp.preconditions
        group Vérification des préconditions
            !foreach $precondition in $dataTemp.preconditions
                $precondition($precondition)
            !endfor
        end
    !endif
!endprocedure



!procedure Draw($data) 
    skinparam style strictuml

    !$entity = $data.entity
    !$name = $data.name
    !$demande = $data.demande
    !$create = $data.create

    title $name


    actor Développeur as Utilisateur #Orange

    ' boundary Constructeur as CLI
    control SuiPro as SuiPro
    participant $entity as Entity

    ' == Interface==

    ' Utilisateur -> CLI : $demande
    ' activate CLI
    ' $generateRequirement($data)

    ' == $name ==

    Utilisateur -> SuiPro : $create
    activate SuiPro #Gray
    deactivate Utilisateur

    opt #LightBlue 
        SuiPro -> SuiPro : Vérifie les préconditions $generateRequirement($data)
        $generatePrecondition($data)
        SuiPro --> Utilisateur ++ : Envoi le message de confirmation
        deactivate SuiPro
    end

    $generatePrecondition($data)

    !if $data.preconditions

        group#Gold #LightGreen Préconditions vérifiées ? [true]
            SuiPro -> Entity ** : $create
            activate Entity
            $generatePostcondition($data)
            Entity --> SuiPro -- : Confirme l'opération
            SuiPro -[#Green]> Utilisateur ++ : Envoi le message de confirmation
        else #Pink false
            SuiPro -[#Red]> Utilisateur : Envoi un message d'erreur
            deactivate SuiPro
        end

    !else 
        
        SuiPro -> Entity ** : $create
        activate Entity
        $generatePostcondition($data)
        Entity -> SuiPro -- : Confirme l'opération
        SuiPro -> Utilisateur ++ : Envoi le message de confirmation
        deactivate SuiPro
    !endif

    ' CLI --> Utilisateur : Affiche le résultat de l'opération

!endprocedure


Draw($dataFormat)